### ISSUE TITLE
Make Prooftree parser less neurotic

### ISSUE THREAD

**Issue by gleachkr** [gleachkr/Carnap-Old#27]
Some things to do:
- [X] Accept subproofs which don't contain any lines other than a termination.
- [X]  Parse the final line of a subproof without assuming that it is a termination. This is a little tricky, since any alphanumeric + underscore string can be a proposition---a nullary rule will not be distinguishable from a line with a single proposition on it. We need to change the syntax to catch this. 
  
  Suggestion 1: propositions cannot be ALL CAPS, zero-premise rules cannot be named by a single character. 
  
  Suggestion 2: sub-proof terminations start with a special character, maybe ':'.
  
  Suggestion 3: all rule invocations (including nullary rules) end a special character, maybe ':'.

**Comment by JakeEhrlich** [comment]
I'm in favor of option 2. I was actually thinking we wanted something like that any way. I was thinking either a 'close' keyword or a slash '/' to signify that the proof has been closed.

**Comment by gleachkr** [comment]
Ok, option 2 it is. We could be flexible and allow "close", "close:", ":", or "/"

**Comment by gleachkr** [comment]
Or better yet, "close", "/", or any alphabetical string followed by ":".

**Comment by JakeEhrlich** [comment]
Sounds good to me!

**Comment by gleachkr** [comment]
Anything else?

**Comment by JakeEhrlich** [comment]
Indentation is picky. We should make that less picky. For instance now that sub proofs are delimited by a 'Show' and some closing mark ':', '/', or 'close' you don't actually need the indentation. I vote to let people indent as they see fit. The primary advantage of this is that people wont run into "off by one space" bugs. That was the primary thing that annoyed people in that programming logics tool I was talking about.

**Comment by gleachkr** [comment]
Ok, that sounds like a good idea. I think we might need a little bit of indentation still, because we allow for partial subproofs to be embedded in a proof that's under development (so, you can stop working on one subproof for a minute, go to another, and then go back). If we drop indentation, then subsequent lines that are supposed to be part of the main proof will get sucked up into an unfinished subproof. 

Maybe we could allow for arbitrary extra whitespace at the beginning of a regular line? So, if you accidentally add an extra space, you're OK, but if you go under the amount of indentation in the subproof, then your line is assumed to be part of the to one of the containing proofs. This would ensure that every indentation level is meaningful (avoiding confusing errors), while allowing different levels of indentation to have different meanings.

**Comment by JakeEhrlich** [comment]
Hrm... That doesn't sound bad. When programming and I need to do something similar I either just use a dummy value like "undefined" or close it off and pretend it is done. So you could have an 'undefined' proves anything justification to close your proof off with while you go work on another sub proof. The error would just be "todo: finish this proof" That said I'm not sure this idea is better. I personally think I would prefer that but I'm not sure what people in general would prefer, particularly people that have never done this before. The more implicit nature of your idea might be easier on them. It's one less thing to remember.

**Comment by gleachkr** [comment]
I think I've got the same "one less thing to remember" intuition about what'd be helpful.

If we go with an "undefined" keyword, then we've either got to display a proof that has no termination line as an error (which means that if you're in the middle of writing something, and you don't have the termination down yet, you'll get an error), or have two ways of getting an unfinished proof, which might be more complexity than we'd want for starting students. 

I'll go ahead and try to allow for whitespace at the beginnings of lines.

**Comment by JakeEhrlich** [comment]
Awesome! One last thing and then I'll have zero complaints I think. The list of numbers that comes after the justification shouldn't be so picky either. Currently it demands that there be no spaces in the comma separated list of numbers. That bothers me though.

**Comment by gleachkr** [comment]
Right, definitely. Nice catch. I'm on my way out, but I'll try to get it tonight.

**Comment by gleachkr** [comment]
Ok, done. The numbers can now be separated by any combination of ' 's and ','s (in case you want to just use spaces as delimiters)

**Comment by gleachkr** [comment]
I'll leave this open till tomorrow in case we think of anything else.
