### ISSUE TITLE
Make a webapp that generates worksheets from query strings

### ISSUE THREAD

**Issue by gleachkr** [gleachkr/Carnap-Old#28]
The idea would be two have two interfaces. One lets you write down a bunch of problems, or even partial derivations, and generates a URL with a query string. The second receives the query string, and regenerates the content previously entered. This would be a really convenient way to distribute problem sets.

**Comment by JakeEhrlich** [comment]
So this is tricky if we don't want to start doing some server side dev (which would involve a lot of decisions I think). It is possible to read GET parameters of a URL in javascript but not possible to read POST. GET places limits on how many bytes we can service and it isn't clear how many. Web browsers and web servers both limit this. For instance Chrome allows around 2000 bytes but apache web servers default to 8000 but some web servers only handle them up to 512! So the weakest link between the web server and the browser determines the maximum length there. The web server can be configured but browsers can't. So assuming we have 2000 bytes can we actually fit say 20 partial derivations? It is pushing it. I doubt we could fit 100 problems on 2000 bytes. Compression might make this practical however, I'm not sure. Still we are walking a tight rope trying to do this with client side only code.

If we did this server side however there is no problem.

**Comment by gleachkr** [comment]
Ah, ok. I didn't know about the byte limit. That makes this a lot less practical for partial derivations. Still might be more convenient (for problems) than making a problem-set manually. But 20 partial derivations in 2000 bytes would definitely be pushing it---the proof of Russell's theorem on the main page right now, for example is about 500 characters. 

Strongly agree, server-side would be better, but that might have to be a longer-term ambition.

**Comment by JakeEhrlich** [comment]
If the problems chosen are randomly generated then the seed of the random number can be used. That doesn't exactly help with the partial derivation issue but it is somthing.

**Comment by gleachkr** [comment]
Right. I had a similar thought---every way we have of generating problems is also a way of coding them. The code of a problem is just where the sentence to be proved goes in the ordering of generated theorems.

**Comment by gleachkr** [comment]
Here's an example URL:

http://gleachkr.github.io/Carnap/Frontend/Ghcjs/Implementations/FromURL/dist/build/FromURL/FromURL.jsexe/index.html?-(P/\Q);-Q\/-P.-(P\/Q);-Q/\-P

I'll try to add some facilities to the ShowThis webapp so that you don't have to write these by hand. The URLs can include unicode logical symbols, so it should be possible to serialize formulas via "show".
