### ISSUE TITLE
Selectable output

### ISSUE THREAD

**Issue by davidfaraci** [gleachkr/Carnap-Old#37]
It would be nice to be able to select text from the right side output for copy/paste purposes.

**Comment by gleachkr** [comment]
Ok. I'll change the reorder-by-dragging set up in the ShowThis webapp so that it uses a "handle", rather than just having you grab the whole problem. You should then be able to select for cut-and-paste in the same way as in the other webapps.

**Comment by gleachkr** [comment]
Ok, this should be fixed by f92ef56d7536cf3dde30e887869e092fd9e38991.
